### ISSUE TITLE
bring back a useful table

### ISSUE THREAD

**Issue by dret** [w3c/tr-pages#60] opened 2018-03-22 11:50 UTC
turning https://www.w3.org/TR/ into a bunch of blocks is a huge step back in terms of how easy it is to understand what @w3c has been doing. the table view was much more accessible, compact, and useful. it's probably just the current web design wave to turn everything and anything into blocks, but in this case, it is a particularly big step back for an organization that should first and foremost make its activities easy to see and follow.

**Comment by tripu** [comment] 2018-03-23 17:05
Duplicate of #27.

**Closed by tripu** 2018-03-23 17:05 UTC
Labels: duplicate, mock-up-1
